name: SonarCloud analysis

on:
  push:
    branches: [ "main", "develop2", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: |
          chmod +x gradlew; ./gradlew build -x test --no-daemon

  sonar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Action Setup
        #uses: SonarSource/sonarcloud-github-action@master
        uses: jinguji/sonarcloud-gradle-github-action@v2

      - name: Scanner Sonar
        run: gradle init sonar-scanner
          -Dsonar.projectKey=mandinga27_spring-boot-backend-apirest \
          -Dsonar.organization=mandinga27 \
          -Dsonar.sources=src/main -Dsonar.tests=src/test \
          -Dsonar.qualitygate.wait=true \                 
          -Dsonar.host.url=https://sonarcloud.io

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt

      - name: Git Test
        run: |
          git status