name: SonarCloud analysis

on:
  push:
    branches: [ "main", "develop2", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.11.1

      - name: Execute Gradle build
        run: ./gradlew build -x test

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          echo ${{ github.workspace }}/build
          echo ls -la '${{ github.workspace }}'/build
          echo $GITHUB_WORKSPACE
  sonar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Action Setup
        #uses: SonarSource/sonarcloud-github-action@master
        uses: jinguji/sonarcloud-gradle-github-action@v2

      - name: Scanner Sonar
        run: sonar-scanner
          -Dsonar.projectKey=mandinga27_spring-boot-backend-apirest \
          -Dsonar.organization=mandinga27 \
          -Dsonar.sources=src/main -Dsonar.tests=src/test \
          -Dsonar.qualitygate.wait=true \                 
          -Dsonar.host.url=https://sonarcloud.io

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt

      - name: Git Test
        run: |
          git status