name: Veracode Static Pipeline Scanner

on:
  push:
    branches:
      - develop2

  workflow_call:
    inputs:
      policy_name:
        required: false
        type: string
      owner:
        required: false
        type: string
      repo:
        required: false
        type: string
      sha:
        required: false
        type: string
      token:
        required: true
        type: string
      ref:
        required: false
        type: string
      create_code_scanning_alert:
        required: false
        type: boolean
      create_issue:
        required: true
        type: boolean
      check_run_id:
        required: true
        type: string
      source_repository:
        required: true
        type: string
      profile_name:
        required: false
        type: string
      break_build_policy_findings:
        required: true
        type: string
      break_build_on_error:
        required: true
        type: string
      filter_mitigated_flaws:
        required: true
        type: string
      language:
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          #cache: 'gradle'
      - run: |
          chmod +x gradlew; ./gradlew clean build -x test
          pwd
          ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/libs/*.jar

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: build/libs/

  invoke-reusable:
    needs: build
    uses: mandinga27/spring-boot-backend-apirest/.github/workflows/sonarcloud.yml@develop2

  veracode-policie-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Veracode Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@0.2.6
        id: upload_and_scan
        with:
          appname: 'spring-boot-backend-apirest'
          version: ${{ github.run_id }}
          filepath: 'build/libs/spring-boot-backend-apirest-0.0.1-SNAPSHOT.jar'
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          #sandboxname: 'Github - ${{ github.ref }}'
          scantimeout: 15
          criticality: 'VeryHigh'
          createprofile: false
        continue-on-error: true

  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Veracode Pipeline Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: build/libs/ # Ruta donde quieres descargar el artefacto

      - name: pipeline-scan action step
        id: pipelien-scan
        uses: veracode/Veracode-pipeline-scan-action@esd-true
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: "build/libs/"
          #request_policy: "VeraDemo Policy"
          debug: 1
          fail_build: false

      - uses: actions/upload-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results
          path: results.json

  veracode_fix:
     needs: pipeline_scan
     runs-on: ubuntu-latest
     name: Veracode Fix
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get flaw file
        uses: actions/download-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results
          path: results.json

      - name: Create fixes from static findings
        id: convert
        uses: Veracode/veracode-fix@main
        with:
          inputFile: filtered_results.json
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey:${{ secrets.VERACODE_API_KEY }}
          source_base_path_1: "com/:src/main/java/com/"
          source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          language: java
          prComment: true
          fixType: single
